apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  test: hola
  nginx.conf: |
    server {
        listen  8080
        server_name localhost;

        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
        }

        error_page 500 502 503 504 /50x.html
        location = ./50x.html {
          root /usr/share/nginx/html;
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vars
data:
  db_user: admin
  db_host: localhost
  script: |
    echo DB_HOST es $DB_HOST Y DB_USER es $DB_USER > /usr/share/nginx/html/index.html
---
apiVersion: v1
kind: Deployment
metadata: 
  name: deploy-test
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          volumeMounts:
          - name: nginx-vol
            mountPath: /etc/nginx/conf.d
          - name: vars-vol
            mountPath: /opt
          env:
            - name: DB_HOST
              valueFrom:
                ConfigMapKeyRef:
                  name: vars
                  key: db_host
            - name: DB_USER
              valueFrom:
                ConfigMapKeyRef:
                  name: vars
                  key: db_user
      volumes:
        - name: nginx-vol
          configMap:
            name: nginx-config
            items:
              - key: nginx
                path: default.conf
        - name: vars-vol
          configMap:
            name: vars
            items:
              - key: script
                path: script.sh
    

