apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "Port mapping change"
  name: deploy-hello-project
  namespace: test-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template: 
    metadata: 
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-pod
        image: nigelpoulton/pluralsight-docker-ci:latest
        ports:
        - containerPort: 8081