apiVersion: v1
kind: Secret
metadata:
  name: MySecret
type: Opaque
stringData:
  user: admin
  password: AgreeMore01
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mycont
    image: nginx:alpine
    volumeMounts:
    - name: test
      mountPath: "/opt"
      readOnly: true
    env:
      - name: DB_USER
        valueFrom:
          secretKeyRef:
            name: MySecret
            key: user
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: MySecret
            key: password
  volumes:
  - name: test
    secret: 
      secretName: MySecret
      items:
      - key: user
        path: user.txt

