apiVersion: v1
kind: Pod
metadata:
  name: readiness-pod
  namespace: default
spec:
  containers:
  - name: readiness-cont
    image: k8s.gcr.io/goproxy:0.1
    ports:
    - containerPort: 8080
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
